env: 
  ticker: MSFT
  interval: 1d
  period: 2y
  train_prop: 0.7
  window_size: 15
  indicators: [MOM, MACD, MFI, RSI, ATR, CO, OBV]  # [MOM, MACD, MFI, RSI, ATR, CO, OBV]
policy: 
  net_arch: 
    vf: [128, 128]
    pi: [128, 64]
  lstm_hidden_size: 64
  n_lstm_layers: 2
  activation_fn: Tanh
ppo: 
  batch_size: 64
  n_steps: 4
  gamma: 0.99
  n_epochs: 5
  clip_range: .2
  verbose: 1
optim: 
  n_episodes: 200
  max_no_improvement_evals: 50
  min_evals: 50                               # must be <= n_episodes
  n_steps_per_episode: -1