a2c: 
  policy: "MlpPolicy"
  policy_kwargs:
    net_arch: 
      vf: [128, 128, 128]
      pi: [64, 64]
  learning_rate: .0007
  n_steps: 5
  gamma: 0.99
  verbose: 1
ppo: 
  policy: "MlpPolicy"
  policy_kwargs:
    net_arch: 
      vf: [128, 128, 128]
      pi: [64, 64]
  learning_rate: .0007
  n_steps: 5
  gamma: 0.99
  n_epochs: 5
  clip_range: .2
  verbose: 1
optim: 
  total_timesteps: 100 
  reward_threshold: 200
  eval_freq: 10
  save_path: .models/